### ISSUE TITLE
[DOXIATOOLS-20] APT anchors are parsed to invalid XML in xdoc book

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia-book-renderer#9]
**[Dave Syer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david_syer)** opened **[DOXIATOOLS-20](https://issues.apache.org/jira/browse/DOXIATOOLS-20?redirect=false)** and commented

APT anchors are parsed to invalid XML in xdoc book.  E.g. start with APT like this

```
{Section Title}

  La la la la

```

and then include this document in a book with "xdoc" format.  You get an invalid XML document which then fails when it is being turned into HTML for the site:

```
[ERROR] Error parsing /home/dsyer/dev/admin/code/target/generated-site/xdoc/reference/jobs.xml: line [-1] Error parsing the model: markup not allowed inside attribute value - illegal <  (position: END_TAG seen ...<section name="<... @1:676) 
org.apache.maven.doxia.parser.ParseException: Error parsing the model: markup not allowed inside attribute value - illegal <  (position: END_TAG seen ...<section name="Add your Own <... @1:676) 
	at org.apache.maven.doxia.parser.AbstractXmlParser.parse(AbstractXmlParser.java:57)
	at org.apache.maven.doxia.module.xdoc.XdocParser.parse(XdocParser.java:99)
	at org.apache.maven.doxia.DefaultDoxia.parse(DefaultDoxia.java:59)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderDocument(DefaultSiteRenderer.java:342)
```

The xml is invlaid because it has `<section name="<a name="Section_Title"/>".../>`.

---
No further details from [DOXIATOOLS-20](https://issues.apache.org/jira/browse/DOXIATOOLS-20?redirect=false)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
